window.COOKING_DATA = {
  ui: {
    ko: {
      home: "처음으로",
      recipe: "전체 레시피",
      back: "이전",
      next: "다음",
      finish: "완성",
      start: "시작",
      done: "완료",
      intro: "요리 소개",
      step: "단계",
      recipeEyebrow: "나중에 다시 볼 수 있어요",
      recipeTitle: "전체 레시피",
      close: "닫기",
      startOver: "처음부터 보기",
    },
    en: {
      home: "Start",
      recipe: "Full Recipe",
      back: "Back",
      next: "Next",
      finish: "Finish",
      start: "Start",
      done: "Done",
      intro: "Introduction",
      step: "Step",
      recipeEyebrow: "KEEP THIS RECIPE",
      recipeTitle: "Full Recipe",
      close: "Close",
      startOver: "Start Over",
    },
    vi: {
      home: "Từ đầu",
      recipe: "Công thức",
      back: "Quay lại",
      next: "Tiếp theo",
      finish: "Hoàn tất",
      start: "Bắt đầu",
      done: "Xong",
      intro: "Giới thiệu",
      step: "Bước",
      recipeEyebrow: "LƯU LẠI CÔNG THỨC",
      recipeTitle: "Công thức đầy đủ",
      close: "Đóng",
      startOver: "Xem lại từ đầu",
    },
  },

  settings: {
    // 얼음이 준비되면 true로 바꾸면 STEP 4와 전체 레시피에 안내가 표시됩니다.
    showIce: false,
  },

  slides: [
    {
      type: "cover",
      image: "./assets/step-6.webp",
      ko: {
        title: "한국 요리\n문화수업",
        foods: "라볶이 & 화채",
        subtitle: "함께 한국 음식을 만들어 봐요!",
      },
      en: {
        title: "Korean\nCooking Class",
        foods: "Rabokki & Hwachae",
        subtitle: "Let's cook Korean food together!",
      },
      vi: {
        title: "Ẩm thực\nHàn Quốc",
        foods: "Rabokki & Hwachae",
        subtitle: "Hãy cùng nhau nấu món Hàn Quốc!",
      },
    },
    {
      type: "intro",
      image: "./assets/step-6.webp",
      ko: {
        eyebrow: "오늘의 한국 요리",
        title: "두 가지 맛을 만나요",
        imageAlt: "완성된 라볶이와 화채",
        dishes: [
          {
            name: "라볶이",
            category: "매콤·달콤한 분식",
            description: "떡볶이에 라면을 더한 요리예요. 쫄깃한 떡과 면을 매콤달콤한 소스에 함께 끓여요.",
          },
          {
            name: "화채",
            category: "시원한 과일 디저트",
            description: "여러 과일을 시원한 음료와 우유에 섞어 먹는 한국식 디저트예요.",
          },
        ],
      },
      en: {
        eyebrow: "TODAY'S KOREAN DISHES",
        title: "Meet Two Favorite Flavors",
        imageAlt: "Finished rabokki and hwachae",
        dishes: [
          {
            name: "Rabokki",
            category: "Spicy-sweet street food",
            description: "Tteokbokki with ramen: chewy rice cakes and noodles simmered together in a spicy-sweet sauce.",
          },
          {
            name: "Hwachae",
            category: "Cool fruit dessert",
            description: "A Korean fruit punch made by mixing fresh fruit with a chilled fizzy, milky drink.",
          },
        ],
      },
      vi: {
        eyebrow: "HAI MÓN HÀN HÔM NAY",
        title: "Khám phá hai hương vị",
        imageAlt: "Rabokki và hwachae đã hoàn thành",
        dishes: [
          {
            name: "Rabokki",
            category: "Món ăn đường phố cay ngọt",
            description: "Tteokbokki kết hợp mì ramen: bánh gạo dẻo và mì được nấu trong sốt cay ngọt.",
          },
          {
            name: "Hwachae",
            category: "Tráng miệng trái cây mát lạnh",
            description: "Món trái cây kiểu Hàn, trộn với nước có ga và sữa, dùng thật lạnh.",
          },
        ],
      },
    },
    {
      type: "soak",
      image: "./assets/step-1.webp",
      ko: {
        eyebrow: "STEP 1 · 먼저 시작해요",
        title: "떡 불리기",
        action: "떡을 물에 담가주세요.",
        followup: "떡이 불려지는 동안 다른 재료를 준비해요.",
        imageAlt: "물이 담긴 그릇에서 떡을 불리는 모습",
      },
      en: {
        eyebrow: "STEP 1 · START HERE",
        title: "Soak the Rice Cakes",
        action: "Put the rice cakes in water.",
        followup: "Prepare the other ingredients while the rice cakes soak.",
        imageAlt: "Rice cakes soaking in a glass bowl of water",
      },
      vi: {
        eyebrow: "BƯỚC 1 · BẮT ĐẦU TẠI ĐÂY",
        title: "Ngâm bánh gạo",
        action: "Cho bánh gạo vào nước để ngâm.",
        followup: "Chuẩn bị các nguyên liệu khác trong lúc ngâm bánh gạo.",
        imageAlt: "Bánh gạo đang ngâm trong tô nước",
      },
    },
    {
      type: "cut",
      image: "./assets/step-2.webp",
      ko: {
        eyebrow: "STEP 2 · 재료 준비",
        title: "재료 썰기",
        action: "먹기 좋은 크기로 잘라주세요.",
        safety: "칼을 사용할 때 조심하세요!",
        hwachae: "수박 · 망고 · 바나나",
        rabokki: "어묵 · 대파",
        imageAlt: "먹기 좋은 크기로 썬 수박, 망고, 바나나와 어묵",
      },
      en: {
        eyebrow: "STEP 2 · PREP THE INGREDIENTS",
        title: "Cut the Ingredients",
        action: "Cut into bite-sized pieces.",
        safety: "Be careful with the knife!",
        hwachae: "Watermelon · Mango · Banana",
        rabokki: "Fish cake · Green onion",
        imageAlt: "Bite-sized watermelon, mango, banana and fish cake on a board",
      },
      vi: {
        eyebrow: "BƯỚC 2 · CHUẨN BỊ NGUYÊN LIỆU",
        title: "Cắt nguyên liệu",
        action: "Cắt thành miếng vừa ăn.",
        safety: "Cẩn thận khi sử dụng dao!",
        hwachae: "Dưa hấu · Xoài · Chuối",
        rabokki: "Chả cá · Hành lá",
        imageAlt: "Dưa hấu, xoài, chuối và chả cá được cắt miếng vừa ăn",
      },
    },
    {
      type: "boil",
      image: "./assets/step-3.webp",
      ko: {
        eyebrow: "STEP 3 · 라볶이 조리",
        title: "재료 넣고 끓이기",
        imageAlt: "떡과 어묵을 라볶이 소스와 함께 끓이는 냄비",
        steps: [
          "준비된 물과 소스를 넣습니다.",
          "잘 섞어주세요.",
          "불려둔 떡의 물을 빼주세요.",
          "떡, 어묵, 대파를 넣습니다.",
          "모든 재료를 함께 끓여주세요.",
        ],
      },
      en: {
        eyebrow: "STEP 3 · COOK THE RABOKKI",
        title: "Add & Boil Together",
        imageAlt: "Rice cakes and fish cake boiling together in rabokki sauce",
        steps: [
          "Add the prepared water and sauce.",
          "Mix well.",
          "Drain the soaked rice cakes.",
          "Add the rice cakes, fish cakes and green onion.",
          "Cook everything together.",
        ],
      },
      vi: {
        eyebrow: "BƯỚC 3 · NẤU RABOKKI",
        title: "Cho vào & nấu cùng nhau",
        imageAlt: "Bánh gạo và chả cá đang được nấu cùng sốt rabokki",
        steps: [
          "Cho phần nước và sốt đã chuẩn bị vào nồi.",
          "Trộn đều.",
          "Để ráo bánh gạo đã ngâm.",
          "Cho bánh gạo, chả cá và hành lá vào.",
          "Nấu tất cả cùng nhau.",
        ],
      },
    },
    {
      type: "hwachae",
      image: "./assets/step-4.webp",
      ko: {
        eyebrow: "STEP 4 · 시원한 디저트",
        title: "화채 만들기",
        steps: ["과일을 그릇에 넣습니다.", "준비된 사이다를 넣습니다.", "준비된 우유를 넣습니다.", "부드럽게 섞어주세요."],
        optional: "더 달게 먹고 싶으면 연유를 더 넣어주세요.",
        ice: "얼음을 조금 넣고 시원하게 즐겨요!",
        imageAlt: "수박, 망고, 바나나가 든 화채",
      },
      en: {
        eyebrow: "STEP 4 · COOL DESSERT",
        title: "Make Hwachae",
        steps: ["Put the fruit in a bowl.", "Add the prepared Sprite.", "Add the prepared milk.", "Mix gently."],
        optional: "Add a little if you want it sweeter.",
        ice: "Add some ice and enjoy it cold!",
        imageAlt: "Hwachae with watermelon, mango and banana",
      },
      vi: {
        eyebrow: "BƯỚC 4 · MÓN TRÁNG MIỆNG MÁT LẠNH",
        title: "Làm Hwachae",
        steps: ["Cho trái cây vào tô.", "Thêm phần Sprite đã chuẩn bị.", "Thêm phần sữa đã chuẩn bị.", "Trộn nhẹ nhàng."],
        optional: "Chỉ thêm một chút nếu bạn muốn ngọt hơn.",
        ice: "Thêm một ít đá và thưởng thức thật mát!",
        imageAlt: "Hwachae với dưa hấu, xoài và chuối",
      },
    },
    {
      type: "ramen",
      image: "./assets/step-5.webp",
      ko: {
        eyebrow: "STEP 5 · 마지막 조리",
        title: "라면사리 넣기",
        action: "라면사리를 넣어주세요.",
        cue: "면이 익을 때까지 끓여요.",
        imageAlt: "라볶이 냄비에 라면사리를 넣는 모습",
      },
      en: {
        eyebrow: "STEP 5 · FINAL COOK",
        title: "Add Ramen Noodles",
        action: "Add the ramen noodles.",
        cue: "COOK UNTIL THE NOODLES ARE READY",
        imageAlt: "A block of ramen noodles being added to the rabokki pot",
      },
      vi: {
        eyebrow: "BƯỚC 5 · NẤU LẦN CUỐI",
        title: "Cho mì ramen vào",
        action: "Cho mì ramen vào nồi.",
        cue: "NẤU ĐẾN KHI MÌ CHÍN",
        imageAlt: "Một vắt mì ramen được cho vào nồi rabokki",
      },
    },
    {
      type: "finish",
      image: "./assets/step-6.webp",
      ko: {
        title: "완성!",
        phrase: "잘 먹겠습니다!",
        translation: "맛있게 드세요!",
      },
      en: {
        title: "Done!",
        phrase: "잘 먹겠습니다!",
        translation: "Enjoy your meal!",
      },
      vi: {
        title: "Xong!",
        phrase: "잘 먹겠습니다!",
        translation: "Chúc ngon miệng!",
      },
    },
  ],

  recipe: {
    ko: {
      title: "라볶이 & 화채",
      subtitle: "집에서 다시 만들어보는 2인분 기본 레시피",
      ingredientsTitle: "재료",
      methodTitle: "만드는 방법",
      ratioTitle: "핵심 비율",
      serving: "2인분",
      foods: [
        {
          id: "rabokki",
          title: "라볶이",
          ingredients: [
            ["떡", "200g"],
            ["라볶이 소스", "100g"],
            ["물", "200mL"],
            ["어묵", "80~100g"],
            ["라면사리", "1개"],
            ["대파", "1/3~1/2대"],
          ],
          steps: [
            "떡이 단단하면 물에 잠시 불립니다.",
            "어묵과 대파를 먹기 좋은 크기로 자릅니다.",
            "냄비에 물과 소스를 넣고 섞습니다.",
            "떡과 어묵을 넣고 함께 끓입니다.",
            "떡이 부드러워지면 라면사리를 넣습니다.",
            "면이 익을 때까지 끓인 뒤 대파를 넣어 마무리합니다.",
          ],
        },
        {
          id: "hwachae",
          title: "화채",
          ingredients: [
            ["수박", "기호에 따라"],
            ["망고", "기호에 따라"],
            ["바나나", "기호에 따라"],
            ["사이다 또는 레몬라임 탄산음료", "300mL"],
            ["우유", "150mL"],
            ["연유", "기호에 따라\n(선택)"],
            ["얼음", "기호에 따라\n(선택)"],
          ],
          ratio: "사이다 : 우유 = 2 : 1",
          note: "좋아하는 과일을 원하는 만큼 준비하세요. 사이다와 우유는 2:1 비율로 넣습니다.",
          steps: [
            "원하는 과일을 먹기 좋은 크기로 자릅니다.",
            "과일을 그릇에 담습니다.",
            "사이다와 우유를 2:1 비율로 넣습니다.",
            "부드럽게 섞습니다.",
            "더 달게 먹고 싶으면 연유를 추가합니다.",
            "원하는 경우 얼음을 넣습니다.",
          ],
        },
      ],
    },
    en: {
      title: "Rabokki & Hwachae",
      subtitle: "A basic 2-serving recipe to make at home",
      ingredientsTitle: "Ingredients",
      methodTitle: "Directions",
      ratioTitle: "Key ratio",
      serving: "2 servings",
      foods: [
        {
          id: "rabokki",
          title: "Rabokki",
          ingredients: [
            ["Rice cakes", "200 g"],
            ["Rabokki sauce", "100 g"],
            ["Water", "200 mL"],
            ["Fish cake", "80–100 g"],
            ["Ramen noodles", "1 pack"],
            ["Green onion", "1/3–1/2 stalk"],
          ],
          steps: [
            "If the rice cakes are firm, soak them briefly in water.",
            "Cut the fish cake and green onion into bite-sized pieces.",
            "Add the water and sauce to a pot and mix.",
            "Add the rice cakes and fish cake, then cook them together.",
            "When the rice cakes are soft, add the ramen noodles.",
            "Cook until the noodles are ready, then finish with the green onion.",
          ],
        },
        {
          id: "hwachae",
          title: "Hwachae",
          ingredients: [
            ["Watermelon", "To taste"],
            ["Mango", "To taste"],
            ["Banana", "To taste"],
            ["Sprite or lemon-lime soda", "300 mL"],
            ["Milk", "150 mL"],
            ["Condensed milk", "To taste\n(Optional)"],
            ["Ice", "To taste\n(Optional)"],
          ],
          ratio: "Sprite : Milk = 2 : 1",
          note: "Prepare as much of your favorite fruit as you like. Add Sprite and milk in a 2:1 ratio.",
          steps: [
            "Cut your favorite fruit into bite-sized pieces.",
            "Put the fruit in a bowl.",
            "Add Sprite and milk in a 2:1 ratio.",
            "Mix gently.",
            "Add condensed milk if you want it sweeter.",
            "Add ice if you like.",
          ],
        },
      ],
    },
    vi: {
      title: "Rabokki & Hwachae",
      subtitle: "Công thức cơ bản cho 2 người để nấu lại tại nhà",
      ingredientsTitle: "Nguyên liệu",
      methodTitle: "Cách làm",
      ratioTitle: "Tỉ lệ chính",
      serving: "2 phần",
      foods: [
        {
          id: "rabokki",
          title: "Rabokki",
          ingredients: [
            ["Bánh gạo rabokki", "200 g"],
            ["Sốt rabokki", "100 g"],
            ["Nước", "200 mL"],
            ["Chả cá", "80–100 g"],
            ["Mì ramen", "1 gói"],
            ["Hành lá", "1/3–1/2 cây"],
          ],
          steps: [
            "Nếu bánh gạo còn cứng, ngâm nhanh trong nước.",
            "Cắt chả cá và hành lá thành miếng vừa ăn.",
            "Cho nước và sốt vào nồi rồi trộn đều.",
            "Cho bánh gạo và chả cá vào nấu cùng nhau.",
            "Khi bánh gạo mềm, cho mì ramen vào.",
            "Nấu đến khi mì chín rồi cho hành lá vào để hoàn thành.",
          ],
        },
        {
          id: "hwachae",
          title: "Hwachae",
          ingredients: [
            ["Dưa hấu", "Tùy thích"],
            ["Xoài", "Tùy thích"],
            ["Chuối", "Tùy thích"],
            ["Sprite hoặc nước ngọt chanh có ga", "300 mL"],
            ["Sữa", "150 mL"],
            ["Sữa đặc", "Tùy thích\n(Không bắt buộc)"],
            ["Đá", "Tùy thích\n(Không bắt buộc)"],
          ],
          ratio: "Sprite : Sữa = 2 : 1",
          note: "Chuẩn bị loại trái cây bạn thích với lượng tùy ý. Cho Sprite và sữa theo tỉ lệ 2:1.",
          steps: [
            "Cắt loại trái cây bạn thích thành miếng vừa ăn.",
            "Cho trái cây vào tô.",
            "Cho Sprite và sữa theo tỉ lệ 2:1.",
            "Trộn nhẹ nhàng.",
            "Thêm sữa đặc nếu bạn muốn ngọt hơn.",
            "Thêm đá nếu muốn.",
          ],
        },
      ],
    },
  },
};
