window.COOKING_DATA = {
  ui: {
    ko: {
      recipe: "전체 레시피",
      back: "이전",
      next: "다음",
      finish: "완성",
      start: "시작",
      done: "완료",
      step: "단계",
      recipeEyebrow: "나중에 다시 볼 수 있어요",
      recipeTitle: "전체 레시피",
      close: "닫기",
      startOver: "처음부터 보기",
      serving: "5명 1조",
    },
    en: {
      recipe: "Full Recipe",
      back: "Back",
      next: "Next",
      finish: "Finish",
      start: "Start",
      done: "Done",
      step: "Step",
      recipeEyebrow: "KEEP THIS RECIPE",
      recipeTitle: "Full Recipe",
      close: "Close",
      startOver: "Start Over",
      serving: "For 5 people",
    },
    vi: {
      recipe: "Công thức",
      back: "Quay lại",
      next: "Tiếp theo",
      finish: "Hoàn tất",
      start: "Bắt đầu",
      done: "Xong",
      step: "Bước",
      recipeEyebrow: "LƯU LẠI CÔNG THỨC",
      recipeTitle: "Công thức đầy đủ",
      close: "Đóng",
      startOver: "Xem lại từ đầu",
      serving: "Dành cho 5 người",
    },
  },

  slides: [
    {
      type: "cover",
      image: "./assets/step-6.webp",
      ko: {
        kicker: "한국 요리 문화수업",
        title: "한국 요리\n문화수업",
        foods: "라볶이 & 화채",
        subtitle: "함께 한국 음식을 만들어 봐요!",
      },
      en: {
        kicker: "KOREAN COOKING CLASS",
        title: "Korean\nCooking Class",
        foods: "Rabokki & Hwachae",
        subtitle: "Let's cook Korean food together!",
      },
      vi: {
        kicker: "LỚP HỌC NẤU MÓN HÀN QUỐC",
        title: "Ẩm thực\nHàn Quốc",
        foods: "Rabokki & Hwachae",
        subtitle: "Hãy cùng nhau nấu món Hàn Quốc!",
      },
    },
    {
      type: "soak",
      image: "./assets/step-1.webp",
      ko: {
        eyebrow: "STEP 1 · 먼저 시작해요",
        title: "떡 불리기",
        action: "떡을 물에 담가주세요.",
        detail: "다른 재료를 준비하는 동안 물에 담가둡니다.",
        tip: "이제 그대로 두고 다음 재료를 준비해요.",
        imageAlt: "물이 담긴 그릇에서 떡을 불리는 모습",
      },
      en: {
        eyebrow: "STEP 1 · START HERE",
        title: "Soak the Rice Cakes",
        action: "Put the rice cakes in water.",
        detail: "Leave them in the water while we prepare the other ingredients.",
        tip: "Leave them here and move to the next step.",
        imageAlt: "Rice cakes soaking in a glass bowl of water",
      },
      vi: {
        eyebrow: "BƯỚC 1 · BẮT ĐẦU TẠI ĐÂY",
        title: "Ngâm bánh gạo",
        action: "Cho bánh gạo vào nước để ngâm.",
        detail: "Ngâm trong lúc chuẩn bị các nguyên liệu khác.",
        tip: "Để bánh gạo ngâm và chuyển sang bước tiếp theo.",
        imageAlt: "Bánh gạo đang ngâm trong tô nước",
      },
    },
    {
      type: "cut",
      image: "./assets/step-2.webp",
      ko: {
        eyebrow: "STEP 2 · 재료 준비",
        title: "과일과 어묵 썰기",
        action: "먹기 좋은 크기로 잘라주세요.",
        safety: "칼을 사용할 때 조심하세요!",
        hwachae: "수박 · 망고 · 바나나",
        rabokki: "어묵",
        imageAlt: "먹기 좋은 크기로 썬 수박, 망고, 바나나와 어묵",
      },
      en: {
        eyebrow: "STEP 2 · PREP THE INGREDIENTS",
        title: "Cut Fruit & Fish Cake",
        action: "Cut into bite-sized pieces.",
        safety: "Be careful with the knife!",
        hwachae: "Watermelon · Mango · Banana",
        rabokki: "Fish cake",
        imageAlt: "Bite-sized watermelon, mango, banana and fish cake on a board",
      },
      vi: {
        eyebrow: "BƯỚC 2 · CHUẨN BỊ NGUYÊN LIỆU",
        title: "Cắt trái cây & chả cá",
        action: "Cắt thành miếng vừa ăn.",
        safety: "Cẩn thận khi sử dụng dao!",
        hwachae: "Dưa hấu · Xoài · Chuối",
        rabokki: "Chả cá",
        imageAlt: "Dưa hấu, xoài, chuối và chả cá được cắt miếng vừa ăn",
      },
    },
    {
      type: "boil",
      image: "./assets/step-3.webp",
      ko: {
        eyebrow: "STEP 3 · 5명 1조",
        title: "재료 넣고 끓이기",
        water: "물",
        sauce: "떡볶이 소스",
        imageAlt: "떡과 어묵을 소스와 함께 끓이는 냄비",
        imageLabel: "처음부터 함께 끓여요",
        steps: [
          "물 500g과 소스 250g을 계량합니다.",
          "냄비에 넣고 잘 섞습니다.",
          "불려둔 떡의 물을 빼주세요.",
          "떡과 어묵을 넣습니다.",
          "모두 함께 끓여주세요.",
        ],
        warning: "소스만 먼저 끓이지 않아요.",
        next: "끓는 동안 화채를 만들어요!",
      },
      en: {
        eyebrow: "STEP 3 · FOR 5 PEOPLE",
        title: "Add & Boil Together",
        water: "Water",
        sauce: "Tteokbokki Sauce",
        imageAlt: "Rice cakes and fish cake boiling together in tteokbokki sauce",
        imageLabel: "BOIL EVERYTHING TOGETHER",
        steps: [
          "Measure 500 g water + 250 g sauce.",
          "Add them to the pot and mix well.",
          "Drain the soaked rice cakes.",
          "Add rice cakes and fish cake.",
          "Cook everything together.",
        ],
        warning: "Do not boil the sauce alone.",
        next: "While it cooks, let's make Hwachae!",
      },
      vi: {
        eyebrow: "BƯỚC 3 · DÀNH CHO 5 NGƯỜI",
        title: "Cho vào & nấu cùng nhau",
        water: "Nước",
        sauce: "Sốt tteokbokki",
        imageAlt: "Bánh gạo và chả cá đang được nấu cùng sốt tteokbokki",
        imageLabel: "NẤU TẤT CẢ CÙNG NHAU",
        steps: [
          "Đong 500 g nước + 250 g sốt.",
          "Cho vào nồi và khuấy đều.",
          "Để ráo bánh gạo đã ngâm.",
          "Cho bánh gạo và chả cá vào.",
          "Nấu tất cả cùng nhau.",
        ],
        warning: "Không đun riêng nước sốt.",
        next: "Trong khi chờ, hãy làm Hwachae!",
      },
    },
    {
      type: "hwachae",
      image: "./assets/step-4.webp",
      ko: {
        eyebrow: "STEP 4 · 시원한 디저트",
        title: "화채 만들기",
        sprite: "사이다",
        milk: "우유",
        steps: ["과일을 큰 그릇에 넣습니다.", "사이다와 우유를 2:1로 넣습니다.", "부드럽게 섞어주세요."],
        optionalTitle: "연유",
        optional: "더 달게 먹고 싶다면 조금 넣어주세요.",
        imageAlt: "수박, 망고, 바나나가 든 화채",
      },
      en: {
        eyebrow: "STEP 4 · COOL DESSERT",
        title: "Make Hwachae",
        sprite: "Sprite",
        milk: "Milk",
        steps: ["Put the fruit in a large bowl.", "Add Sprite and milk in a 2:1 ratio.", "Mix gently."],
        optionalTitle: "Condensed milk",
        optional: "Add a little only if you want it sweeter.",
        imageAlt: "Hwachae with watermelon, mango and banana",
      },
      vi: {
        eyebrow: "BƯỚC 4 · MÓN TRÁNG MIỆNG MÁT LẠNH",
        title: "Làm Hwachae",
        sprite: "Sprite",
        milk: "Sữa",
        steps: ["Cho trái cây vào tô lớn.", "Thêm Sprite và sữa theo tỉ lệ 2:1.", "Trộn nhẹ nhàng."],
        optionalTitle: "Sữa đặc",
        optional: "Chỉ thêm một chút nếu bạn muốn ngọt hơn.",
        imageAlt: "Hwachae với dưa hấu, xoài và chuối",
      },
    },
    {
      type: "ramen",
      image: "./assets/step-5.webp",
      ko: {
        eyebrow: "STEP 5 · 마지막 조리",
        title: "라면사리 넣기",
        action: "라면사리를 넣어주세요.",
        cue: "면이 익을 때까지 끓여요",
        detail: "소스가 너무 졸았다면 물을 조금 추가하세요.",
        imageAlt: "떡볶이 냄비에 라면사리를 넣는 모습",
      },
      en: {
        eyebrow: "STEP 5 · FINAL COOK",
        title: "Add Ramen Noodles",
        action: "Add the ramen noodles.",
        cue: "COOK UNTIL THE NOODLES ARE READY",
        detail: "If the sauce is too thick, add a little water.",
        imageAlt: "A block of ramen noodles being added to the tteokbokki pot",
      },
      vi: {
        eyebrow: "BƯỚC 5 · NẤU LẦN CUỐI",
        title: "Cho mì ramen vào",
        action: "Cho mì ramen vào nồi.",
        cue: "NẤU ĐẾN KHI MÌ CHÍN",
        detail: "Nếu sốt quá đặc, hãy thêm một ít nước.",
        imageAlt: "Một vắt mì ramen được cho vào nồi tteokbokki",
      },
    },
    {
      type: "finish",
      image: "./assets/step-6.webp",
      ko: {
        kicker: "요리 완성",
        title: "완성!",
        phrase: "잘 먹겠습니다!",
        translation: "맛있게 드세요!",
      },
      en: {
        kicker: "COOKING COMPLETE",
        title: "Done!",
        phrase: "잘 먹겠습니다!",
        translation: "Enjoy your meal!",
      },
      vi: {
        kicker: "ĐÃ NẤU XONG",
        title: "Xong!",
        phrase: "잘 먹겠습니다!",
        translation: "Chúc ngon miệng!",
      },
    },
  ],

  recipe: {
    ko: {
      title: "라볶이 & 화채",
      subtitle: "다낭 한국 요리 문화수업 · 5명 1조",
      metrics: [
        ["500g", "물"],
        ["250g", "떡볶이 소스"],
        ["2 : 1", "사이다 : 우유"],
      ],
      sections: [
        ["떡 불리기", ["떡 500g을 물에 담가둡니다.", "다른 재료를 준비하는 동안 계속 불립니다."]],
        ["재료 썰기", ["수박, 망고, 바나나를 먹기 좋은 크기로 자릅니다.", "어묵도 먹기 좋은 크기로 자릅니다.", "칼을 사용할 때 조심하세요."]],
        ["떡볶이 끓이기", ["물 500g과 떡볶이 소스 250g을 계량합니다.", "냄비에 물과 소스를 넣어 잘 섞습니다.", "떡의 물을 빼고, 떡과 어묵을 냄비에 넣습니다.", "모든 재료를 처음부터 함께 끓입니다."]],
        ["화채 만들기", ["과일을 큰 그릇에 넣습니다.", "사이다와 우유를 2:1 비율로 넣습니다.", "부드럽게 섞습니다.", "더 달게 먹고 싶다면 연유를 조금 넣습니다."]],
        ["라면사리 넣기", ["떡과 어묵이 어느 정도 익으면 라면사리를 넣습니다.", "면이 익을 때까지 끓입니다.", "소스가 너무 졸았다면 물을 조금 추가합니다."]],
      ],
      highlight: "중요: 떡볶이 소스만 먼저 끓이지 말고, 떡과 어묵을 넣어 처음부터 함께 끓여주세요.",
    },
    en: {
      title: "Rabokki & Hwachae",
      subtitle: "Da Nang Korean Cooking Class · Team of 5",
      metrics: [
        ["500 g", "Water"],
        ["250 g", "Tteokbokki sauce"],
        ["2 : 1", "Sprite : Milk"],
      ],
      sections: [
        ["Soak the rice cakes", ["Put 500 g of rice cakes in water.", "Leave them soaking while you prepare the other ingredients."]],
        ["Cut the ingredients", ["Cut watermelon, mango and banana into bite-sized pieces.", "Cut the fish cake into bite-sized pieces.", "Be careful with the knife."]],
        ["Cook the tteokbokki", ["Measure 500 g of water and 250 g of tteokbokki sauce.", "Add the water and sauce to the pot and mix well.", "Drain the rice cakes, then add the rice cakes and fish cake.", "Cook everything together from the start."]],
        ["Make the hwachae", ["Put the fruit into a large bowl.", "Add Sprite and milk in a 2:1 ratio.", "Mix gently.", "For extra sweetness, add a little condensed milk."]],
        ["Add the ramen", ["When the rice cakes and fish cake are nearly cooked, add the ramen noodles.", "Cook until the noodles are ready.", "If the sauce is too thick, add a little water."]],
      ],
      highlight: "Important: Do not boil the sauce alone. Add the rice cakes and fish cake, then cook everything together from the start.",
    },
    vi: {
      title: "Rabokki & Hwachae",
      subtitle: "Lớp học nấu món Hàn tại Đà Nẵng · Nhóm 5 người",
      metrics: [
        ["500 g", "Nước"],
        ["250 g", "Sốt tteokbokki"],
        ["2 : 1", "Sprite : Sữa"],
      ],
      sections: [
        ["Ngâm bánh gạo", ["Cho 500 g bánh gạo vào nước.", "Ngâm trong lúc chuẩn bị các nguyên liệu khác."]],
        ["Cắt nguyên liệu", ["Cắt dưa hấu, xoài và chuối thành miếng vừa ăn.", "Cắt chả cá thành miếng vừa ăn.", "Cẩn thận khi sử dụng dao."]],
        ["Nấu tteokbokki", ["Đong 500 g nước và 250 g sốt tteokbokki.", "Cho nước và sốt vào nồi rồi khuấy đều.", "Để ráo bánh gạo, sau đó cho bánh gạo và chả cá vào.", "Nấu tất cả cùng nhau ngay từ đầu."]],
        ["Làm hwachae", ["Cho trái cây vào tô lớn.", "Thêm Sprite và sữa theo tỉ lệ 2:1.", "Trộn nhẹ nhàng.", "Nếu muốn ngọt hơn, thêm một ít sữa đặc."]],
        ["Cho mì ramen vào", ["Khi bánh gạo và chả cá gần chín, cho mì ramen vào.", "Nấu đến khi mì chín.", "Nếu sốt quá đặc, hãy thêm một ít nước."]],
      ],
      highlight: "Quan trọng: Không đun riêng nước sốt. Cho bánh gạo và chả cá vào rồi nấu tất cả cùng nhau ngay từ đầu.",
    },
  },
};
